### PR TITLE
[#95] Upgrade prometheus-operator monitoring to v0.55.1

### PR DESCRIPTION
**Pull request by brusdev**

### CODE REVIEW

**Comment by jeremyary** [comment]
hey @brusdev seems that vet's identified an issue around a missing dependency declaration or similar, could you PTAL? Thanks!!

**Comment by brusdev** [comment]
@jeremyary this issue was fixed in go 1.17, see https://github.com/kubernetes-sigs/controller-tools/issues/643
I have just pushed a commit to update the github workflow too

**Review by tchughesiv — CHANGES_REQUESTED** [review]
please rebase on our `next` branch and change the PR to that branch

**Comment by brusdev** [comment]
@jeremyary @tchughesiv I rebased on `next` branch

**Review by tchughesiv — APPROVED** [review]
lgtm

**Pull request merged**
