### PR TITLE
ocp 4.4 branch in master README

### PR DESCRIPTION
**Pull request by tchughesiv**
Signed-off-by: tchughesiv <tchughesiv@gmail.com>

### CODE REVIEW

**Comment by bmozaffa** [comment]
@jeremyary did we figure out how to go about this? At one point we talked about having just a `master` and a `next` branch. Thoughts, Tommy and Jeremy, on whether the current pattern is the best way to move forward or not.

**Comment by tchughesiv** [comment]
my preference would be a stable branch, besides master, that supports all ocp versions. last time i tried to use master, i had issues.

**Comment by bmozaffa** [comment]
We have features that became supported at one point or other, are you suggesting that branch would always be the most behind? Therefore it would not support features that rely on some newer versions?

**Comment by tchughesiv** [comment]
i'm more suggesting that we have a separate branch that only gets the latest from master once it's been proven all is well with the change(s). more like a gating situation. we should definitely merge master changes into this separate "stable" branch often but only after working through bugs in master.

**Comment by bmozaffa** [comment]
Gotcha... so two separate conversations, then.

1- We need to continually maintain utils for at least two k8s versions. Do we do that by always keeping two branches and removing others? If we have master and branch1, which should track what, and what should branch1 be called? Potentially scenarios:
a- master is always the latest, and older snapshots are called `last-release` or similar
b- branch called `next` will target latest/upcoming version, and master support stable release
c- master is always the latest and new branch will be created for every release explicitly supported

There are more options and these are just examples. Branches diverge, for example if we need to fix a bug for an older k8s, or support a feature differently in the latest as we do in an older k8s release. It would be nice to not constantly create and retire branches, but is it doable and can we reconcile changes so it will be only fast-forwards at some point?

2- You worry about master being an experimental branch, and wants to have a stable one. What will be our criteria for merging into this stable branch? What would we do to make sure it's not broken, the way master has been found to be in the past?

Jeremy will be back on Monday. Let me know how your time looks, and if one of you can spend some time figuring these out.

**Pull request closed without merging**
